"""Run after static entry/assets changes; commit generated pwa-assets.js with them."""
import hashlib, json, pathlib, re
root = pathlib.Path(__file__).resolve().parents[1]
entries = ['index.html', 'v16.html', 'v17.html', 'guest.html']
paths = set(entries + ['manifest.webmanifest', 'guest.webmanifest', 'assets/icons/icon.svg'])
for entry in entries:
    html = (root / entry).read_text()
    for url in re.findall(r'(?:src|href)=[\"\']([^\"\']+)', html):
        path = url.split('?')[0].split('#')[0]
        if not path or ':' in path: continue
        if not (root / path).is_file(): raise SystemExit(f'{entry}: missing resource {path}')
        paths.add(path)
# Icons referenced by manifests; validate every manifest path too.
for manifest in ['manifest.webmanifest', 'guest.webmanifest']:
    for icon in json.loads((root / manifest).read_text())['icons']:
        paths.add(icon['src'].removeprefix('./'))
paths = sorted(paths)
hash_ = hashlib.sha256()
for path in paths:
    hash_.update(path.encode()); hash_.update((root / path).read_bytes())
hash_.update((root / 'sw.js').read_bytes())
output = '/* Generated by scripts/update-pwa-cache.py; do not edit. */\n'
output += 'self.PWA_VERSION = ' + json.dumps(hash_.hexdigest()[:16]) + ';\n'
output += 'self.PWA_ASSETS = ' + json.dumps(['./' + p for p in paths], indent=2) + ';\n'
(root / 'pwa-assets.js').write_text(output)
print(f'Validated {len(paths)} resources; version {hash_.hexdigest()[:16]}')
